all: elastic_1km_npb.pdf

elastic_1km_npb.pdf: elastic_1km_npb.tex \
		authorlist_npb.tex \
		introduction.tex \
		experimental_apparatus.tex \
		beam_optics.tex \
		data_taking.tex \
		differential_cross_section.tex \
		data_table.tex \
		coulomb.tex \
		conclusions.tex \
		acknowledgements.tex
	pdflatex elastic_1km_npb.tex
