all: elastic_1km_npb.pdf

elastic_1km_npb.pdf: elastic_1km_npb.tex authorlist_npb.tex introduction.tex experimental_apparatus.tex\
		data_taking.tex differential_cross_section.tex data_table.tex coulomb.tex
	pdflatex elastic_1km_npb.tex
