all: elastic_1km_epjc.pdf

elastic_1km_epjc.pdf: elastic_1km_epjc.tex \
		abstract.tex \
		authorlist_epjc.tex \
		introduction.tex \
		experimental_apparatus.tex \
		beam_optics.tex \
		data_taking.tex \
		differential_cross_section.tex \
		data_table.tex \
		coulomb.tex \
		fig/fit_exp1/table_data.tex \
		fig/fit_exp3/table_data.tex \
		conclusions.tex \
		acknowledgements.tex \
		bibliography.tex
	pdflatex elastic_1km_epjc.tex
