#!/bin/bash

tar czvf "elastic_1km_sources.tar.gz"\
	elastic_1km_epjc.tex \
	authorlist_epjc.tex \
	authorlist_data.tex \
	abstract.tex \
	introduction.tex \
	experimental_apparatus.tex \
	beam_optics.tex \
	data_taking.tex \
	differential_cross_section.tex \
	data_table.tex \
	coulomb.tex \
	conclusions.tex \
	acknowledgements.tex \
	bibliography.tex \
	fig/*.pdf \
	fig/fit_exp1/*.pdf \
	fig/fit_exp1/*.tex \
	fig/fit_exp3/*.pdf \
	fig/fit_exp3/*.tex \
	svepjc3.clo \
	svglov3.clo \
	svjour3.cls
