#!/bin/bash

gvim -p \
	elastic_90m_npb.tex \
	abstract.tex \
	introduction.tex \
	experimental_apparatus.tex \
	data_taking.tex \
	differential_cross_section.tex \
	results.tex \
	conclusion.tex \
	acknowledgements.tex
