all: elastic_90m_epjc.pdf


elastic_90m_epjc.pdf: elastic_90m_epjc.tex authorlist_epjc.tex introduction.tex experimental_apparatus.tex\
		data_taking.tex differential_cross_section.tex
	pdflatex elastic_90m_epjc.tex
