all: elastic_90m_npb.pdf


elastic_90m_npb.pdf: elastic_90m_npb.tex authorlist_npb.tex introduction.tex experimental_apparatus.tex\
		data_taking.tex differential_cross_section.tex
	pdflatex elastic_90m_npb.tex
