#!/bin/bash

gvim -p \
	thesis.tex \
	introduction.tex \
	elastic.tex \
	totem.tex \
	simu_reco.tex \
		elasticReco.tex \
	alignment.tex \
	sigma_tot.tex \
		extrapolation.tex \
	appendices.tex \
	references.bib
