#!/bin/bash

dir=`date +"%Y_%m_%d"`
dir="release $dir"

if [ -f "$dir" ]
then
	echo "ERROR: directory '$dir' already exists. Remove it first"
	exit 1
fi

mkdir "$dir"

cp "combined_epl.pdf" "$dir/full.pdf"

mkdir -p "$dir/source"
mkdir -p "$dir/source/fig"

cp "combined_epl.tex" "$dir/source/"

cp "fig/sigma_tot_el_inel_cmp_big.pdf" "$dir/source/fig"
cp "fig/sigma_el_to_sigma_tot.pdf" "$dir/source/fig"

cd "$dir/source"
tar czvf ../source.tar.gz *
cd ".."
rm -rf "source"
